const LV=[
{n:"The first night",intro:"Rain is running through the lane. Amara has her baby against her chest and one small hand in hers. Her husband's family has put her outside. She has no key, no room and almost no money. Before morning, she needs somewhere dry.",sky:["#172c35","#657d83"],search:["The flooded lane","wood, cloth and odd tools"],tasks:[{t:"Warm clothes for the children",need:{cloth:2}},{t:"Hot meal from the roadside stall",need:{coins:10}},{t:"Deposit on a rented room",need:{coins:35}}]},
{n:"Somewhere dry",intro:"The rented room is better than the street, but only just. The window hangs from one hinge, the roof leaks and the mattress is a bare frame. It is not home yet. It can become one.",sky:["#30454a","#9a8f7b"],search:["Back lots and skips","planks, rags and metal"],tasks:[{t:"Clear the broken furniture",need:{labor:1}},{t:"Replace the window",need:{wood:2,tools:1}},{t:"Patch the roof",need:{wood:3}},{t:"Buy a mattress and blankets",need:{cloth:3,coins:15}}]},
{n:"The kitchen",intro:"An old stove flares and the wall catches. Amara gets the children out before the smoke becomes a fire. When it is safe, she sees what she must learn: survival is not only about fixing what broke. It is about making the next break less likely.",sky:["#4a2d22","#a5562f"],search:["The repair yard","wire, parts and timber"],tasks:[{t:"Make the kitchen safe",need:{coins:5}},{t:"Wire the kitchen safely",need:{parts:2,tools:1}},{t:"Replace the stove",need:{parts:2,coins:20}}]},
{n:"The garden",intro:"Behind the room is hard ground and a collapsed fence. A neighbour says beans once grew here. Food that does not have to be bought every day could change the family's future.",sky:["#315541","#b6c28e"],search:["Sheds and market edges","boards, tools and spare pipe"],tasks:[{t:"Rebuild the fence",need:{wood:3}},{t:"Buy soil and seed",need:{coins:15}},{t:"Fit a hand pump",need:{parts:1,wood:1}}]},
{n:"The great rain",intro:"Three days of rain turn the road into a river. Water reaches the doorstep, then the floor. The children climb onto the table while Amara saves what she can. This time she has neighbours.",sky:["#263a43","#66808b"],search:["The flooded road","sandbags, boards and pipe"],tasks:[{t:"Sandbag the doorway",need:{cloth:3,wood:1}},{t:"Pump out the floor",need:{parts:2,tools:1}},{t:"Dry the bedding",need:{coins:12}},{t:"Reseal the floor",need:{wood:3,coins:10}}]},
{n:"The turning point",intro:"The house is still modest, but it holds its warmth. Amara has started taking sewing work. The first car she can afford is an embarrassment: scratched paint, tired tyres and a starter that sometimes needs persuasion. It is hers. It can take her to opportunity.",sky:["#3e4e50","#c6b27d"],search:["The mechanic's lane","scrap, cloth and small tools"],tasks:[{t:"Repair the old car",need:{parts:3,coins:20}},{t:"Buy a safer set of tyres",need:{coins:25}},{t:"Insulate the bedroom window",need:{cloth:2,tools:1}},{t:"Build a proper workbench",need:{wood:4,tools:1}}]},
{n:"The first business",intro:"A market woman offers Amara a corner for her sewing. A small stall becomes a real livelihood if she can stock it, keep customers and survive the bad weeks.",sky:["#5c4b39","#d8b06a"],search:["Market back lanes","offcuts, thread and scrap iron"],tasks:[{t:"Repair the sewing machine",need:{parts:2,coins:15}},{t:"Pay the market permit",need:{coins:30}},{t:"Build the stall counter",need:{wood:4,tools:1}},{t:"Stock cloth for the week",need:{cloth:5}}]},
{n:"Shelter",intro:"The house is not a palace. That was never the promise. It is warm, secure and full of things made possible one ordinary day at a time. Kemi has school. Tobi has grown. Amara has work, a car that starts, neighbours who know her name and a door she can choose to open.",sky:["#4c4938","#e0b36a"],search:["The town market","cloth, tools and useful odds and ends"],tasks:[{t:"Buy a table and two chairs",need:{wood:4,cloth:1}},{t:"Keep Kemi in school",need:{coins:30}},{t:"Install a dependable light",need:{parts:1,coins:15}},{t:"Put food aside for a difficult week",need:{coins:20}}]}];
const OUT=["The room is small, but it has a door. Amara sits with the children until the rain softens. She has somewhere to begin.","The drip over the bed stops. A neighbour leaves rice at the door. Amara realises the first thing she is building is not the room. It is a network of people.","The new stove works. She writes the repair date on a scrap of paper and pins it to the wall. Next time, she will know what failed and why.","Green shoots appear. Kemi calls the garden a kingdom. Amara laughs and lets her believe it.","The water falls. The neighbours share tools and food. The house is damaged, but it stands. Amara understands that strength can be shared.","The old car starts on the second try. It is ugly and loud. Amara smiles anyway. It takes her to the market, the clinic, school and work. That is enough.","The stall earns its first proper week. A customer returns with a friend. Amara begins writing down costs instead of guessing them. A business is born from ordinary discipline.","At night the lamp glows. Kemi asks if they are staying. Amara looks at the children, then at the door.\n\n\"Yes.\"\n\nLater, she sees someone standing outside in the rain. She opens the door.\n\n\"Come inside.\""];
const LINES=["The children are warm enough to sleep.","The landlord slides a key across the table.","The repaired window lets in morning light.","The roof holds through the next shower.","The wiring is safe. The fear leaves slowly.","The stove burns cleanly.","The fence holds.","Clear water runs from the pump.","The sandbags hold the first surge.","The room dries.","The car starts. It sounds terrible, but it starts.","The new tyres grip the wet road.","The machine makes a clean stitch.","The permit is stamped.","The stall counter is crooked, sturdy and hers.","A teacher writes Kemi's name in the register."];
const DF={easy:{c:.7,d:1,e:.10,h:7,t:9,z:1.25,sp:1.4,r:15,m:1,coins:40},hard:{c:1,d:2,e:.22,h:11,t:14,z:1,sp:1.9,r:11,m:1.5,coins:25},harder:{c:1.35,d:3,e:.34,h:15,t:20,z:.72,sp:2.5,r:8,m:2,coins:15}};
const SETTING={id:"west-african-inspired",tagline:"Survive the night. Build a home. Build a livelihood. Build a community.",choose:"Choose a difficulty. You can replay completed chapters for a better score."};
